###########
# site.title, site.url, site.author.name

title:   'Coen Roest'
url:     'http://coenroet.github.io/'
author:
  name:  'Coen Roest'


########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

permalink: /:title.html

exclude:
- README.md


safe: true
lsi: false

